#!/bin/sh

# MAKE SURE THE FILE IS EXECUTABLE!!!

BSPWM_PATH="$HOME/.config/bspwm"

pgrep -x sxhkd > /dev/null || sxhkd &

laptop=eDP-1
external=HDMI-1

is_external_connected=$(xrandr -q | grep "$external connected")
if [[ $is_external_connected ]]; then
    echo "Entering multi-screen setup"
    xrandr --output $external --primary --mode 1920x1080 --rotate normal --output $laptop --mode 1920x1080 --rotate normal --left-of $external
    bspc monitor $external -d 5 6 7 8 9 10
    bspc monitor $laptop -d 1 2 3 4
else
    echo "Entering single-screen setup"
    xrandr --output $laptop --primary --mode 1920x1080 --rotate normal 
    bspc monitor $laptop -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

# Rules for bspwm
bspc rule -a Zathura state=tiled
bspc rule -a Joplin desktop=10
bspc rule -a Todoist desktop=4
bspc rule -a whatsapp-nativefier-d52542 desktop=9
bspc rule -a TelegramDesktop desktop=9

# System programs
~/.config/polybar/forest/launch.sh > /dev/null &
dunst > /dev/null &
~/.fehbg > /dev/null &

# Programs on startup
if [[ -x $HOME/bin/startup ]]; then
    $HOME/bin/startup
else
    notify-send -u critical "Startup file not found or not executable"
fi

bspc desktop -f 5

