#!/bin/sh

# MAKE SURE THE FILE IS EXECUTABLE!!!

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/bin/monitors

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

# Rules for bspwm
bspc rule -a Zathura state=tiled
bspc rule -a Joplin desktop=10
bspc rule -a Todoist desktop=4
bspc rule -a whatsapp-nativefier-d52542 desktop=9
bspc rule -a TelegramDesktop desktop=9

# System programs
~/.config/polybar/forest/launch.sh > /dev/null &
dunst > /dev/null &
~/.fehbg > /dev/null &

bspc desktop -f 4
bspc desktop -f 5

