#! /bin/sh

# MAKE SURE THE FILE IS EXECUTABLE!!!

pgrep -x sxhkd > /dev/null || sxhkd &

laptop=eDP-1
external=HDMI-1

if [[ $(xrandr -q | grep "$external connected") ]]; then
    xrandr --output $external --primary --mode 1920x1080 --rotate normal --output $laptop --mode 1920x1080 --rotate normal --left-of $external
    bspc monitor $external -d 1 2 3 4 5 6
    bspc monitor $laptop -d 7 8 9 10
else
    xrandr --output $laptop --primary --mode 1920x1080 --rotate normal 
    bspc monitor $laptop -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/polybar/forest/launch.sh
