#!/bin/bash

### Apps, Launcher & Co.
# Terminal emulator
super + Return
	alacritty

# Program launcher (dmenu and rofi)
super + @space
    $HOME/.config/polybar/forest/scripts/launcher.sh

# Applications
super + {_, shift + }w
    firefox{_, --private-window}

super + e
    [[ $(pgrep sublime) ]] && subl -n || subl

super + d
    pcmanfm

super + x
    dmenufm

# Patch while autostart does not work
super + Home
    $HOME/bin/startup

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd

super + {_, shift + }Pause
    {dunstctl close-all, $HOME/bin/toggle-dunst}

# power hotkeys

super + Delete
    $HOME/.config/polybar/forest/scripts/powermenu.sh

super + F5
    $HOME/bin/monitors

#
# Media keys
#

XF86AudioRaiseVolume
    amixer -q sset Master 5%+

XF86AudioLowerVolume
    amixer -q sset Master 5%-

XF86AudioMute
    amixer -q sset Master toggle

XF86MonBrightnessDown
    brightnessctl -e -d intel_backlight set '5%-'

XF86MonBrightnessUp
    brightnessctl -e -d intel_backlight set '+5%'

XF86Sleep
    systemctl suspend

XF86AudioPlay
    playerctl play-pause
        
XF86AudioNext
    playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86WebCam
    sed -i 's/card [0-9]/card {0,1}/' $HOME/.asoundrc

XF86Calculator
    kcalc

XF86TouchpadToggle
    $HOME/bin/toggle-touchpad

Print
    flameshot gui

# bspwm hotkeys

# quit/restart bspwm
super + alt + shift + {q,r}
    bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
    bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
    bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
    bspc node -s biggest.local

# rotate the current node 90 degrees
super + r
    bspc node -R 90

super + n
    bspc node -B

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
    bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
    bspc node -f {next,prev}.local

# focus the last node/desktop
super + {_,shift + }Tab
    bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
    bspc pointer -g {move,resize_side,resize_corner}
    bspc wm -h off; \
    bspc node {older,newer} -f; \
    bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '{1-9,10}'

# previous/next desktop in current monitor
super + {_, shift + }{Left,Right}
    bspc {desktop -f,node -d} {prev,next}.local

# previous/next occupied desktop in current monitor
super + ctrl + {_, shift + }{Left,Right}
    bspc {desktop -f,node -d} {prev,next}.occupied.local

# previous/next monitor
super + {Down,Up}
    bspc monitor -f {prev,next}

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
    bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
    bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

